openapi: 3.0.3
info:
  title: Happy-Plant API Documentation
  description: |-
    This page serves as documentation for our Happy-Plant API which is used in our App Happy-Plant.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: plant
    description: Endpoints for plant
  - name: inventory
    description: A list of all plants that have not been placed in a room yet
  - name: species
    description: Endpoints for the app's plant encyclopedia
  - name: room
    description: Endpoints for room
  - name: assignment
    description: Endpoints for assignment
  - name: user
    description: Endpoint for user

paths:
  /plants:
    get:
      tags:
        - plant
      summary: Get a list of all the user's plants
      operationId: getPlants
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plant'
        '400':
          description: Bad Request
        '404':
          description: No Plants found
    post:
      tags:
        - plant
      summary: Add a new plant to the user's account
      operationId: addPlant
      requestBody:
        description: Create a new plant
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plant'
          application/xml:
            schema:
              $ref: '#/components/schemas/Plant'
        required: true
      responses:
        '201':
          description: Plant saved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plant'
            application/xml:
              schema:
                $ref: '#/components/schemas/Plant'
        '400':
          description: Invalid input
        '422':
          description: Validation exception

  /plant/{plantId}:
    get:
      tags:
        - plant
      summary: Find plant by ID
      description: Returns a single plant, including needs and assignments
      operationId: getPlantById
      parameters:
        - name: plantId
          in: path
          description: ID of plant to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plant'
            application/xml:
              schema:
                $ref: '#/components/schemas/Plant'
        '400':
          description: Invalid ID supplied
        '404':
          description: Plant not found
    put:
      tags:
        - plant
      summary: Update plant
      description: Change the plant's name, species etc.
      operationId: updatePlant
      parameters:
        - name: plantId
          in: path
          description: ID of plant to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update an existent plant in the user's list
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plant'
          application/xml:
            schema:
              $ref: '#/components/schemas/Plant'
      responses:
        '200':
          description: plant successfully updated
        '400':
          description: Invalid ID supplied
        '404':
          description: Plant not found
    delete:
      tags:
        - plant
      summary: Deletes a plant
      description: delete a plant
      operationId: deletePlant
      parameters:
        - name: plantId
          in: path
          description: ID of plant to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: plant successfully deleted
        '400':
          description: Invalid ID supplied
        '404':
          description: Plant not found

  /plants/{plantId}/assignments/{assignmentId}:
    put:
      tags:
        - plant
      summary: Update plant assignment "last done" date
      description: Specify when an assignment was done the last time
      operationId: updatePlantAssignment
      parameters:
        - name: plantId
          in: path
          description: ID of plant to update
          required: true
          schema:
            type: integer
            format: int64
        - name: assignmentId
          in: path
          description: ID of assignment to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update an existent plant's "last done" date for an assignment
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Assignment'
          application/xml:
            schema:
              $ref: '#/components/schemas/Assignment'
      responses:
        '200':
          description: plant assignment successfully updated
        '400':
          description: Invalid ID supplied
        '404':
          description: Plant assignment not found

  /inventory:
    get:
      tags:
        - inventory
      summary: Returns a list of non-placed plants
      description: Returns a list of all plants not yet placed in a room
      operationId: getInventory
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plant'

  /species:
    get:
      tags:
        - species
      summary: Get all species
      description: Get a list of all plant species
      operationId: getSpecies
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Species'
        '404':
          description: Not found

  /species/{speciesId}:
    get:
      tags:
        - species
      summary: Get species by id
      description: Find a plant species by its id
      operationId: getSpeciesById
      parameters:
        - name: speciesId
          in: path
          description: ID of species that needs to be fetched
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Species'
            application/xml:
              schema:
                $ref: '#/components/schemas/Species'
        '400':
          description: Invalid ID supplied
        '404':
          description: Species not found

  /rooms:
    get:
      tags:
        - room
      summary: Get a list of all the user's rooms
      operationId: getRooms
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
        '400':
          description: Bad Request
        '404':
          description: No Rooms found
    post:
      tags:
        - room
      summary: Add a new room to the user's account
      operationId: addRoom
      requestBody:
        description: Create a new plant
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'
          application/xml:
            schema:
              $ref: '#/components/schemas/Room'
        required: true
      responses:
        '201':
          description: Room saved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
            application/xml:
              schema:
                $ref: '#/components/schemas/Room'
        '400':
          description: Invalid input
        '422':
          description: Validation exception


  /rooms/{roomId}:
    get:
      tags:
        - room
      summary: Find room by ID
      description: Returns a single room
      operationId: getRoomById
      parameters:
        - name: roomId
          in: path
          description: ID of room to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
            application/xml:
              schema:
                $ref: '#/components/schemas/Room'
        '400':
          description: Invalid ID supplied
        '404':
          description: Room not found
    delete:
      tags:
        - room
      summary: Deletes a room
      description: delete a room
      operationId: deleteRoom
      parameters:
        - name: roomId
          in: path
          description: ID of room to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Room successfully deleted
        '400':
          description: Invalid ID supplied
        '404':
          description: Room not found


  /rooms/{roomId}/plants:
    get:
      tags:
        - room
      summary: Get a list of all the plants in a room
      operationId: getPlantsInRoom
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plant'
        '400':
          description: Invalid ID
        '404':
          description: No Plants found
    post:
      tags:
        - room
      summary: Add a new plant to a specific room
      operationId: addPlantToRoom
      requestBody:
        description: Add a new plant to this room
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plant'
          application/xml:
            schema:
              $ref: '#/components/schemas/Plant'
        required: true
      responses:
        '201':
          description: Plant was successfully added to this room
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plant'
            application/xml:
              schema:
                $ref: '#/components/schemas/Plant'
        '400':
          description: Invalid input
        '422':
          description: Validation exception


  /rooms/{roomId}/plants/{plantId}:
    put:
      tags:
        - room
      summary: Update place of a plant in a room
      description: Move a plant's spot inside of a room
      operationId: updatePlantInRoom
      parameters:
        - name: roomId
          in: path
          description: ID of room to look in
          required: true
          schema:
            type: integer
            format: int64
        - name: plantId
          in: path
          description: ID of plant to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update a plant's place inside a room
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pixel'
      responses:
        '200':
          description: plant placement successfully updated
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found

    delete:
      tags:
        - room
      summary: Removes a plant from a room
      description: Remove a plant from a room
      operationId: deletePlantFromRoom
      parameters:
        - name: roomId
          in: path
          description: ID of room to look in
          required: true
          schema:
            type: integer
            format: int64
        - name: plantId
          in: path
          description: ID of plant to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Plant successfully deleted from the room
        '400':
          description: Invalid ID supplied
        '404':
          description: Plant not found

  /assignments:
    get:
      tags:
        - assignment
      summary: Gets all active assignments
      description: Returns a list of all assignments that are active / due
      operationId: getAssignments
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Assignment'
        '404':
          description: No assignments found


  /user/logout:
    get:
      tags:
        - user
      summary: Logs out current logged in user session
      description: ''
      operationId: logoutUser
      parameters: []
      responses:
        default:
          description: successful operation
  /user/{username}:
    get:
      tags:
        - user
      summary: Get user by user name
      description: ''
      operationId: getUserByName
      parameters:
        - name: username
          in: path
          description: 'The name that needs to be fetched. Use user1 for testing. '
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    put:
      tags:
        - user
      summary: Update user
      description: This can only be done by the logged in user.
      operationId: updateUser
      parameters:
        - name: username
          in: path
          description: name that need to be deleted
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent user in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: successful operation
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
        - name: username
          in: path
          description: The name that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
components:
  schemas:
    Species:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100000
        name:
          type: string
          example: butterfly orchid
        latinName:
          type: string
          example: phalaenopsis
        picturePath:
          type: string
          example: /assets/pictures/abcdefg.jpg
        family:
          type: string
          example: orchids
        description:
          type: string
          example: lorem ipsum
        needs:
          $ref: '#/components/schemas/Needs'
    Needs:
      type: object
      properties:
        intervals:
          type: object
          description: Intervals in days for repeating assignments
          properties:
            watering:
              type: integer
              example: 2
            cutting:
              type: integer
              example: 365
            fertilizing:
              type: integer
              example: 30
            repotting:
              type: integer
              example: 365
            repositioning:
              type: integer
              example: 150
    Assignment:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        assignmentType:
            $ref: '#/components/schemas/AssignmentType'
        lastDone:
          type: string
          format: date-time
          example: 2024-03-20T09:12:28Z
    Room:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        grid:
          type: array
          items:
            type: array
            items:
              type: integer
    Plant:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Bob
        species:
          $ref: '#/components/schemas/Species'
        assignments:
          type: array
          items:
              $ref: '#/components/schemas/Assignment'
        picturePath:
          type: string
          example: /assets/pictures/abcdefg.jpg
    AssignmentType:
      type: string
      enum:
        - watering
        - cutting
        - fertilizing
        - repotting
        - repositioning
    Pixel:
      type: object
      properties:
        x:
          type: integer
        y:
          type: integer