version: "3.3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_happyplant
    ports:
      - "8086:8080"
    volumes:
     - ./swagger:/usr/share/nginx/html/swagger
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/swagger/openapi.yaml